### Simple PyTorch Project from building dataset, architecting the network and training and prediction 

In [3]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

In [25]:
class NumberSumDataset(Dataset):
    def __init__(self, data_range = (1, 10)):
        self.numbers = list(range(data_range[0], data_range[1]))

    def __getitem__(self, index):
        number1 = float(self.numbers[index // len(self.numbers)])
        number2 = float(self.numbers[index % len(self.numbers)])
        return torch.tensor([number1, number2]), torch.tensor([number1 + number2])

    def __len__(self):
        return len(self.numbers) ** 2

In [26]:
dataset = NumberSumDataset(data_range = (1, 100))

In [27]:
for i in range(5):
    print(dataset[i])

(tensor([1., 1.]), tensor([2.]))
(tensor([1., 2.]), tensor([3.]))
(tensor([1., 3.]), tensor([4.]))
(tensor([1., 4.]), tensor([5.]))
(tensor([1., 5.]), tensor([6.]))


In [28]:
class MPL(nn.Module):
    def __init__(self, input_size):
        super(MPL, self).__init__()
        self.hidden_layer = nn.Linear(input_size, 128)
        self.output_layer = nn.Linear(128, 1)
        self.activation = nn.ReLU()

    def forward(self, x):
        x = self.activation(self.hidden_layer(x))
        return self.output_layer(x)

In [30]:
dataset = NumberSumDataset(data_range = (1, 100))
dataloader = DataLoader(dataset, batch_size = 100, shuffle = True)
model = MPL(input_size = 2)
loss_function = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr = 0.001)

In [31]:
for epoch in range(10):
    total_loss = 0.0 
    for number_pair, sums in dataloader:
        predictions = model(number_pair)
        loss = loss_function(predictions, sums)
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()

        total_loss = total_loss + loss.item()
    print("Epoch {}: Sum of Batch Losses = {:.5f}".format(epoch+1, total_loss))
        

Epoch 1: Sum of Batch Losses = 181461.07164
Epoch 2: Sum of Batch Losses = 1563.44097
Epoch 3: Sum of Batch Losses = 385.45975
Epoch 4: Sum of Batch Losses = 26.49727
Epoch 5: Sum of Batch Losses = 11.19898
Epoch 6: Sum of Batch Losses = 9.02268
Epoch 7: Sum of Batch Losses = 8.05083
Epoch 8: Sum of Batch Losses = 7.16758
Epoch 9: Sum of Batch Losses = 6.82355
Epoch 10: Sum of Batch Losses = 6.00637


In [32]:
model(torch.tensor([3.0, 7.0]))

tensor([10.4946], grad_fn=<ViewBackward0>)